TASK_REGISTRY = {
    "send-appointment-reminders-hourly": {
        "name": "send-appointment-reminders-hourly",
        "task": "tasks.scheduled.appointment_reminders.send_upcoming_appointment_reminders",
        "description": "Dispatches SMS, Email, and Push reminders for appointments within the next 24 hours.",
        "cron": "0 * * * *",
        "queue": "notifications",
        "category": "Messaging",
    },
    "send-payment-reminders-daily": {
        "name": "send-payment-reminders-daily",
        "task": "tasks.scheduled.payment_reminders.send_pending_payment_reminders",
        "description": "Sends payment reminders for pending M-Pesa or invoice billing transactions.",
        "cron": "0 9 * * *",
        "queue": "payments",
        "category": "Billing",
    },
    "trigger-followup-reminders-daily": {
        "name": "trigger-followup-reminders-daily",
        "task": "tasks.scheduled.followup_reminders.send_post_consultation_followups",
        "description": "Sends automated post-consultation care check-ins and questionnaire links.",
        "cron": "0 10 * * *",
        "queue": "notifications",
        "category": "Clinical Care",
    },
    "flag-inactive-accounts-weekly": {
        "name": "flag-inactive-accounts-weekly",
        "task": "tasks.scheduled.inactive_accounts.check_and_notify_inactive_users",
        "description": "Identifies users with 180+ days of inactivity and sends retention notices.",
        "cron": "0 2 * * 0",
        "queue": "default",
        "category": "Account Maintenance",
    },
    "generate-daily-admin-report": {
        "name": "generate-daily-admin-report",
        "task": "tasks.scheduled.daily_reports.generate_and_send_daily_digest",
        "description": "Compiles daily platform metrics, appointment totals, and revenue digests.",
        "cron": "55 23 * * *",
        "queue": "reports",
        "category": "Analytics",
    },
    "purge-expired-sessions-and-files": {
        "name": "purge-expired-sessions-and-files",
        "task": "tasks.scheduled.database_cleanup.cleanup_expired_data",
        "description": "Purges temporary upload files, expired auth tokens, and orphaned records.",
        "cron": "0 3 * * *",
        "queue": "maintenance",
        "category": "System Maintenance",
    },
    "archive-audit-logs-monthly": {
        "name": "archive-audit-logs-monthly",
        "task": "tasks.scheduled.audit_archiver.archive_old_audit_logs",
        "description": "Archives audit logs older than 90 days into encrypted cold storage blobs.",
        "cron": "0 1 1 * *",
        "queue": "maintenance",
        "category": "Security & Compliance",
    },
    "automated-database-backup": {
        "name": "automated-database-backup",
        "task": "tasks.scheduled.backup_scheduler.trigger_database_backup",
        "description": "Triggers PostgreSQL database snapshot backup and uploads to cloud storage.",
        "cron": "0 4 * * *",
        "queue": "maintenance",
        "category": "Disaster Recovery",
    },
    "send-patient-notification-digest": {
        "name": "send-patient-notification-digest",
        "task": "tasks.scheduled.notification_digest.send_bundled_notification_digest",
        "description": "Bundles unread daily notifications into a single email summary for patients.",
        "cron": "0 18 * * *",
        "queue": "notifications",
        "category": "Messaging",
    },
    "cleanup-telehealth-video-sessions": {
        "name": "cleanup-telehealth-video-sessions",
        "task": "tasks.scheduled.video_session_cleanup.purge_stale_video_rooms",
        "description": "Detects ended or abandoned WebRTC video rooms and releases WebSockets.",
        "cron": "*/15 * * * *",
        "queue": "video",
        "category": "Telehealth",
    },
}
