"""add appointment time and location

Revision ID: 148dbde18e6a
Revises: ae4bd68448fb
Create Date: 2026-07-31 21:02:21.546590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '148dbde18e6a'
down_revision = 'ae4bd68448fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=False))
        batch_op.alter_column('appointment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointment_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.drop_column('location')
        batch_op.drop_column('appointment_time')

    # ### end Alembic commands ###
