"""add checkout request identifiers to payments

Revision ID: 90626314d261
Revises: 714636ebbc69
Create Date: 2026-08-01 11:23:50.163636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90626314d261'
down_revision = '714636ebbc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_checkout_request_id'), ['checkout_request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_checkout_request_id'))
        batch_op.drop_column('merchant_request_id')
        batch_op.drop_column('checkout_request_id')
    # ### end Alembic commands ###
